/* build-cases.cjs
   Writes the two shared case definitions into index.html as an inline fallback.

   index.html fetches cases/halyard-v3.json and cases/brightwater-v2.json at load.
   On file:// and on any host that blocks the fetch, the fetch fails and the page
   falls back to the copy this script writes between the two BUILD markers, so the
   drill still runs from a folder on a laptop with no server.

   Run:  node build-cases.cjs
   The JSON files are the source of truth. Never hand-edit the generated block. */

var fs = require("fs");
var path = require("path");

var ROOT = __dirname;
var HTML = path.join(ROOT, "index.html");
var START = "/* BUILD:CASES-START";
var END = "/* BUILD:CASES-END */";

function load(name) {
  var p = path.join(ROOT, "cases", name);
  var raw = fs.readFileSync(p, "utf8");
  var obj = JSON.parse(raw);
  check(obj, name);
  return obj;
}

/* the checks that would otherwise only show up as a blank card in front of a player */
function check(c, name) {
  var need = ["version", "date", "company", "threshold", "ledger", "groups", "cards"];
  need.forEach(function (k) {
    if (!c[k]) throw new Error(name + ": missing " + k);
  });
  var byAcct = {};
  c.ledger.forEach(function (r) { byAcct[r[0]] = r; });
  c.cards.forEach(function (card) {
    var r = byAcct[card.acct];
    if (!r) throw new Error(name + ": card " + card.n + " points at account " + card.acct + ", which is not in the ledger");
    if (r[2] !== card.prior || r[3] !== card.current) {
      throw new Error(name + ": card " + card.n + " figures do not tie to the ledger for account " + card.acct);
    }
    if (card.key !== "flag" && card.key !== "stand") throw new Error(name + ": card " + card.n + " has key " + card.key);
    if (!card.why || !card.tell) throw new Error(name + ": card " + card.n + " is missing why or tell");
  });
}

var one = load("halyard-v3.json");
var two = load("brightwater-v2.json");

var block =
  START + "  generated by build-cases.cjs, " + new Date().toISOString().slice(0, 10) + ".\n" +
  "   Source of truth: cases/" + one.version + ".json and cases/" + two.version + ".json.\n" +
  "   Used only when the fetch of those files fails, which is what happens on file://. */\n" +
  "var CASE1_FALLBACK = " + JSON.stringify(one) + ";\n" +
  "var CASE2_FALLBACK = " + JSON.stringify(two) + ";\n" +
  END;

var html = fs.readFileSync(HTML, "utf8");
var a = html.indexOf(START);
var b = html.indexOf(END);
if (a === -1 || b === -1) throw new Error("index.html is missing the BUILD:CASES markers");
html = html.slice(0, a) + block + html.slice(b + END.length);
fs.writeFileSync(HTML, html);

console.log("index.html fallback rewritten from " + one.version + " and " + two.version +
  " (" + one.cards.length + " + " + two.cards.length + " cards).");
